### ISSUE TITLE
websocket-server is no longer on npm

### ISSUE THREAD

**Issue by ValkyrieUK** [browserquest/BrowserQuest#161]
* websocket-server has been unpublished https://github.com/StreamMachine/StreamMachine/issues/27
* Suggested replacement is ws

**Comment by knownasilya** [comment]
Should probably close this issue :+1:

**Comment by EddieOne** [comment]
We're using stvrbbns implementation with socket.io, thanks. Only issue we had was with socket.io trying to auto connect while BQ expects closed connections on failed logins.

**Comment by knownasilya** [comment]
@EddieOne that's what I meant, because his solution #162 was merged, so this issue should be closed.

**Comment by ValkyrieUK** [comment]
All is solved, closing this.
