### ISSUE TITLE
Simple Question about Map making...?

### ISSUE THREAD

**Issue by lunarcontrol** [browserquest/BrowserQuest#198]
This is probably a really dumb question..

How do you specify where players can and cannot walk? I can't seem to figure it out by looking at the map? Is it hard coded into the game somewhere?

Why are the "blocking" boxes not put on the edges? Is in in a layer that i am not seeing?

Here is what i'm talking about: 
![Image of Map](http://i.imgur.com/bXLyTy5.png)

Thanks for the help in advance!

**Comment by ghost** [comment]
I can't broadly answer that question, add me on skype and I'll explain how it works. Flavius201202

**Comment by lunarcontrol** [comment]
I added you.. Thanks for everything m8 :)

**Comment by phinolex** [comment]
Hi ! :)

This is not really complicated.

I explain to you :

-Open tiled

-In the "tilesheet" right click on the image in question.
![screenbo](https://cloud.githubusercontent.com/assets/1743597/13056843/4e13620e-d418-11e5-9e1c-cdd2041777d4.png)
- select "tiles of property"

![screen2bo](https://cloud.githubusercontent.com/assets/1743597/13056897/c980fb40-d418-11e5-85a5-08ac6892609b.png)

c → collision: for walls and other sprites which block the player;
You just have to remove it for no longer have collision on that tile. 

I hope to have helped you!

Sorry for my bad English. :s

**Comment by lunarcontrol** [comment]
Thanks! I was just using the tile blocking layer but this will be better in some cases! Thanks again!

**Comment by lzbk** [comment]
It's way too late… sorry about that, I haven't worked on this project for a whiiiiiiile… and unfortunately I won't anytime soon. But I feel it is useful to mention that the wiki has loads of useful info:
https://github.com/browserquest/BrowserQuest/wiki/Create-a-map-using-tiled-map-editor#tile-properties
Plus, that type of info would be more useful to others in the wiki as opposed to closed issues ;)
