### ISSUE TITLE
Switch to Socket.IO?

### ISSUE THREAD

**Issue by Aaron1011** [browserquest/BrowserQuest#92]
I think that we should consider switching to [Socket.IO](http://socket.io/). It automatically selects the best real-time transport method if Websockets are not available. This would allow BrowserQuest to run in more browsers (and on PAAS providers like Heroku, which don't support Websockets).

**Comment by knownasilya** [comment]
Can also be closed, since #162 was merged

**Comment by justinclift** [comment]
Cool, thanks for the heads up. :smile:
